version: '3'
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - microservice
      - redis
    networks:
      - app-network

  db:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  microservice:
    image: your-microservice-image-name
    command: npm run start:dev
    networks:
      - app-network
    build:
      context: ./microservice
    ports:
      - "4000:4000"
    depends_on:
        - redis

  # Redis Cache Service
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
