version: '3'
services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
